version: '3.3'

services:
  db:
    image:  mariadb:10.3.11
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: media_file_system
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.8-php7.1-apache
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: media_file_system
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - "wp:/var/www/html:rw"
      - "./vendor:/var/www/html/vendor:ro"
      - ".:/var/www/html/wp-content/plugins/media-file-system:ro"

  wp-cli:
    image: "wordpress:cli-2.1-php7.1"
    restart: always
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    depends_on:
      - "db"
    volumes:
      - "wp:/var/www/html:rw"
      - "./install-wp.sh:/usr/local/bin/install-wp:ro"
      - ".:/var/www/html/wp-content/plugins/media-file-system:ro"

  wp_phpunit:
    image: "killua99/wordpress-phpunit:latest"
    volumes:
      - ".:/app"
      - "testsuite:/tmp"

  mysql_phpunit:
    image: "mariadb:10.3.11"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "media_file_system_test"
      MYSQL_ROOT_PASSWORD: ""

volumes:
  db_data: {}
  wp: {}
  testsuite: {}